# Generated by Django 4.2.7 on 2025-09-20 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del documento', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre original del archivo', max_length=255, verbose_name='Nombre del archivo')),
                ('mime_type', models.CharField(help_text='Tipo MIME del archivo', max_length=100, verbose_name='Tipo MIME')),
                ('size_bytes', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes', verbose_name='Tamaño en bytes')),
                ('bucket_key', models.CharField(help_text='Clave o ruta del archivo en el bucket de almacenamiento', max_length=500, verbose_name='Clave del bucket')),
                ('file_hash', models.CharField(blank=True, help_text='Hash SHA-256 del archivo para verificación de integridad', max_length=64, verbose_name='Hash del archivo')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del documento', verbose_name='Descripción')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Etiquetas para categorizar el documento', verbose_name='Etiquetas')),
                ('validation_status', models.CharField(blank=True, choices=[(None, 'Sin validación'), ('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], help_text='Estado actual del proceso de validación', max_length=1, null=True, verbose_name='Estado de validación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(help_text='Empresa propietaria del documento', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(help_text='Usuario que subió el documento', on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.ForeignKey(help_text='Entidad de negocio asociada al documento', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.entity', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del flujo de validación', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el flujo de validación está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('document', models.OneToOneField(help_text='Documento asociado al flujo de validación', on_delete=django.db.models.deletion.CASCADE, related_name='validation_flow', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Flujo de validación',
                'verbose_name_plural': 'Flujos de validación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del paso de validación', primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Orden jerárquico del paso (mayor número = mayor jerarquía)', verbose_name='Orden')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', help_text='Estado actual del paso', max_length=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('approver', models.ForeignKey(help_text='Usuario responsable de aprobar este paso', on_delete=django.db.models.deletion.CASCADE, related_name='validation_steps', to=settings.AUTH_USER_MODEL, verbose_name='Aprobador')),
                ('validation_flow', models.ForeignKey(help_text='Flujo de validación al que pertenece el paso', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='documents.validationflow', verbose_name='Flujo de validación')),
            ],
            options={
                'verbose_name': 'Paso de validación',
                'verbose_name_plural': 'Pasos de validación',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ValidationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la acción', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('A', 'Aprobar'), ('R', 'Rechazar')], help_text='Tipo de acción realizada', max_length=1, verbose_name='Acción')),
                ('reason', models.TextField(blank=True, help_text='Razón o comentario de la acción', verbose_name='Razón')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actor', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.PROTECT, related_name='validation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('document', models.ForeignKey(help_text='Documento sobre el que se realizó la acción', on_delete=django.db.models.deletion.CASCADE, related_name='validation_actions', to='documents.document', verbose_name='Documento')),
                ('validation_step', models.ForeignKey(help_text='Paso de validación sobre el que se realizó la acción', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='documents.validationstep', verbose_name='Paso de validación')),
            ],
            options={
                'verbose_name': 'Acción de validación',
                'verbose_name_plural': 'Acciones de validación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='validationstep',
            index=models.Index(fields=['validation_flow', 'order'], name='documents_v_validat_68f03b_idx'),
        ),
        migrations.AddIndex(
            model_name='validationstep',
            index=models.Index(fields=['status'], name='documents_v_status_22f546_idx'),
        ),
        migrations.AddIndex(
            model_name='validationstep',
            index=models.Index(fields=['approver'], name='documents_v_approve_b2e883_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validationstep',
            unique_together={('validation_flow', 'order')},
        ),
        migrations.AddIndex(
            model_name='validationflow',
            index=models.Index(fields=['is_active'], name='documents_v_is_acti_aec0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='validationflow',
            index=models.Index(fields=['created_at'], name='documents_v_created_cd710c_idx'),
        ),
        migrations.AddIndex(
            model_name='validationaction',
            index=models.Index(fields=['document'], name='documents_v_documen_5005bf_idx'),
        ),
        migrations.AddIndex(
            model_name='validationaction',
            index=models.Index(fields=['validation_step'], name='documents_v_validat_868dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='validationaction',
            index=models.Index(fields=['actor'], name='documents_v_actor_i_8d1f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='validationaction',
            index=models.Index(fields=['action'], name='documents_v_action_6eeaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='validationaction',
            index=models.Index(fields=['created_at'], name='documents_v_created_9b7369_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'entity'], name='documents_d_company_b503f0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['validation_status'], name='documents_d_validat_bbb925_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['mime_type'], name='documents_d_mime_ty_29cc61_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='documents_d_file_ha_a7f76e_idx'),
        ),
    ]
